/*
 * (C) Copyright 2017 msgoon6 (miguel.alezander.mejia@outlook.com).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Contributors:
 *     Miguel Alexander Mejía Broncano
 */
package generador;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Scanner;
import javax.swing.JFileChooser;

/**
 *
 * @author msgoon6 (miguel.alezander.mejia@outlook.com)
 */
public class PRINCIPAL extends javax.swing.JFrame {

    JFileChooser chooser;

    /**
     * Creates new form PRINCIPAL
     */
    public PRINCIPAL() {
        initComponents();
        salidaa.setVisible(false);
        lblsel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jButton1 = new javax.swing.JButton();
        salidaa = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblsel = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        durac = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Seleccionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Seleccione la ruta del proyecto a analizar");

        lblsel.setText("PROYECTO SELECCIONADO");

        jButton2.setText("Generar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Duración");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salidaa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1))
                            .addComponent(lblsel))
                        .addGap(0, 151, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(durac, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblsel)
                        .addGap(34, 34, 34)
                        .addComponent(salidaa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(durac, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Inicializar Variables y Elementos
        salidaa.setVisible(false);
        lblsel.setVisible(false);
        //Seleccionar la carpeta del proyecto a analizar
        chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("Seleccione la ruta del proyecto");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            salidaa.setText(chooser.getSelectedFile().toString());
            salidaa.setVisible(true);
            lblsel.setVisible(true);
        } else {
            salidaa.setText("Nada Seleccionado ");
            salidaa.setVisible(true);
            lblsel.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Tiempo invertido
        Date inicio = new Date();
        //conocer mi SO
        String so = System.getProperty("os.name");
        //Determinar el separador para rutas
        String separador = "";
        if (so.equals("Linux")) {
            separador = "/";
        } else {
            separador = "\\";
        }
        //crear rutas importantes
        
        String directorio = "C:\\Users\\Fabian\\Documents\\unitTests\\WebGrafRiobamba\\GraficasRiobamba\\GraficasRiobamba\\src\\test\\servicios"; //ruta pruebas
        //String directorio2 = "C:\\Users\\Fabian\\Documents\\unitTests\\WebGrafRiobamba\\GraficasRiobamba\\GraficasRiobamba\\src\\main\\java\\com\\grafrio\\GraficasRiobamba\\service"; // ruta a leer
          String directorio2 = "C:\\Users\\Fabian\\Documents\\unitTests\\WebGrafRiobamba\\GraficasRiobamba\\GraficasRiobamba\\src\\main\\java\\com\\grafrio\\GraficasRiobamba\\test\\service"; // ruta a leer
          
          /*
          
          
          //crear rutas importantes
          String directorio = "C:\\Users\\Fabian\\Documents\\unitTests\\CONTRATO\\test\\funciones"; //ruta pruebas
          //String directorio2 = "C:\\Users\\Fabian\\Documents\\unitTests\\WebGrafRiobamba\\GraficasRiobamba\\GraficasRiobamba\\src\\main\\java\\com\\grafrio\\GraficasRiobamba\\service"; // ruta a leer
            String directorio2 = "C:\\Users\\Fabian\\Documents\\unitTests\\CONTRATO\\src\\java\\funciones"; // ruta a leer
            
            
            
            
            */
            
        try {
            //fecha y hora para la carpeta
            String timeLog = new SimpleDateFormat("yyyyMMdd_HHmmss").format(Calendar.getInstance().getTime());
            //existe la carpeta...???
            File f = new File(directorio + "_" + timeLog);
            if (!f.exists()) {
                //crear la carpeta
                File carpeta = new File(directorio + "_" + timeLog);
                carpeta.mkdirs();
            }
            //operar en archivos
            File entrada = new File(directorio2);
            if (entrada.exists()) {
                //Seleccionar los Archivos del directorio
                File[] archivos = entrada.listFiles();
                //Recorrer cada archivo
                for (File archivo : archivos) {
                    try {
                        //Obtener el nombre del archivo
                        String nn = archivo.getName();
                        //Quitar la extensión del archivo
                        nn = nn.substring(0, nn.length() - 5);
                        BufferedWriter writer = null;
                        //Crear un archivo con el nombre de la clase agregado el nombre clave Test y la extensión {filename} + Test.java
                        writer = new BufferedWriter(new FileWriter(directorio + "_" + timeLog + "/" + nn + "Test.java", true));
                        //Escribe la part inicial de la clase
                        writer.write("package servicios_" + timeLog + ";\n\n"
                              /*  + "import com.grafrio.GraficasRiobamba.entities.*;\n"
                                + "import funciones.*;\n"*/
                            
                        		+ "import com.grafrio.GraficasRiobamba.entities.*;\n"
                                +"import servicios.*;\n"
                                +"import com.grafrio.GraficasRiobamba.test.service.*;\n"
                                + "import java.util.List;\n"
                                + "import java.util.Date;\n"
                                + "import org.junit.After;\n"
                                + "import org.junit.AfterClass;\n"
                                + "import static org.junit.Assert.*;\n"
                                + "import org.junit.Before;\n"
                                + "import org.junit.BeforeClass;\n"
                                + "import org.junit.Test;\n\n"
                                + "public class " + nn + "Test" + " {\n\n"
                                + "    public " + nn + "Test() " + "{\n"
                                + "    }\n"
                                + "\n"
                                + "    @BeforeClass\n"
                                + "    public static void setUpClass() {\n"
                                + "    }\n"
                                + "\n"
                                + "    @AfterClass\n"
                                + "    public static void tearDownClass() {\n"
                                + "    }\n"
                                + "\n"
                                + "    @Before\n"
                                + "    public void setUp() {\n"
                                + "    }\n"
                                + "\n"
                                + "    @After\n"
                                + "    public void tearDown() {\n"
                                + "    }\n");
                        //select, (insert, update, delete funcionan de manera similar)
                        Scanner scanner = new Scanner(archivo);
                        String metodo = "";
                        boolean band = false;
                        //Recorrer la clase por líneas
                        
                        
                        
                        //Recorrer la clase por l�neas
                        while (scanner.hasNextLine()) {
                            final String lineFromFile = scanner.nextLine();
                            //Busca la palabra reservada "public" para encontrar los m�todos
                            if (lineFromFile.toLowerCase().contains("public")) {
                                metodo = lineFromFile;
                                band = true;
                            }
                            //Si encontr� alg�n m�todo
                            if (band) {
                                try {
                                    //Revisa si existe alguna palabra reservada de SQL
                                    if ((lineFromFile.toLowerCase().contains("insertar"))) {
                                        //Separa el m�todo en partes para obtener el tipo de respuesta
                                        String[] partes = metodo.split("\\(");
                                        String[] partes2 = metodo.split("\\(");
                                        //Separa el m�todo en partes para obtener los par�metros
                                        String[] parametros = partes2[1].split("\\)");
                                        try {
                                            parametros = parametros[0].split(", ");
                                        } catch (Exception e) {
                                            parametros = null;
                                        }
                                        //Escribir el nombre del caso de prueba y el fragmento para tomar el tiempo
                                        if (parametros == null || (parametros.length == 1 && parametros[0].length() <= 1)) {
                                            partes = partes[0].split(" ");
                                            writer.write("\n@Test\n"
                                                    + "    public void test" + partes[partes.length - 1] + "() throws Exception {\n"
                                                    + "        System.out.println(\"" + partes[partes.length - 1] + "\");\n"
                                                    + "        String metodo = \"" + partes[partes.length - 1] + "\";\n"
                                                    + "        String clase = \"" + nn + "\";\n"
                                                    + "        Date vinicio = new Date();\n"
                                                    + "        Boolean expResult = true;\n");
                                            //Inicializar los par�metros seg�n los encontrados entre los ()
                                            String tmp = partes[partes.length - 2];
                                            //Revisar tipos de datos nativos
                                            if (tmp.equals("int") || tmp.equals("Integer")) {
                                                writer.write("        " + partes[partes.length - 2] + " result = 0;\n");
                                            } else {
                                                if (tmp.equals("String")) {
                                                    writer.write("        " + partes[partes.length - 2] + " result = \"\";\n");
                                                } else {
                                                    if (tmp.equals("boolean") || tmp.equals("Boolean")) {
                                                        writer.write("        " + partes[partes.length - 2] + " result = false;\n");
                                                    } else {
                                                        writer.write("int " + partes[partes.length - 2] + " result = 0;\n");
                                                    }
                                                }
                                            }
                                            //Realizar la prueba del resultado del Test
                                            writer.write("        try {\n"
                                                    + "            result = " + nn + "." + partes[partes.length - 1] + "();\n"
                                                    + "        } catch (Exception e) {\n");
                                            //Revisar tipos de datos nativos
                                            if (tmp.equals("int") || tmp.equals("Integer")) {
                                                writer.write("        result = 0;\n");
                                            } else {
                                                if (tmp.equals("String")) {
                                                    writer.write("        result = \"\";\n");
                                                } else {
                                                    if (tmp.equals("boolean") || tmp.equals("Boolean")) {
                                                        writer.write("        result = false;\n");
                                                    } else {
                                                        writer.write("        result = 0;\n");
                                                    }
                                                }
                                            }
                                            //Realizar la prueba del resultado del Test
                                            writer.write("        }\n"
                                                    + "        Boolean res = false;\n"
                                                    + "        if (result == 0) {\n"
                                                    + "            res = true;\n"
                                                    + "        } else {\n"
                                                    + "            res = false;\n"
                                                    + "        }\n"
                                                    + "        assertEquals(expResult, res);\n"
                                                    + "        Date vfinal = new Date();\n"
                                                    + "        long duracion = Util.DiferenciaFechas(vinicio, vfinal);\n"
                                                    + "        Util.exportar(clase, metodo, duracion);\n"
                                                    
                                                    + "    }");
                                        } else {
                                            //Escribir el nombre del caso de prueba y el fragmento para tomar el tiempo
                                            partes = partes[0].split(" ");
                                            writer.write("\n@Test\n"
                                                    + "    public void test" + partes[partes.length - 1] + "() throws Exception {\n"
                                                    + "        System.out.println(\"" + partes[partes.length - 1] + "\");\n"
                                                    + "        String metodo = \"" + partes[partes.length - 1] + "\";\n"
                                                    + "        String clase = \"" + nn + "\";\n"
                                                    + "        Date vinicio = new Date();\n"
                                            );
                                            int i = 1;
                                            for (String param : parametros) {
                                                //Revisar tipos de datos nativos
                                                String[] tipoarr = param.split(" ");
                                                if (tipoarr[0].equals("int") || tipoarr[0].equals("Integer")) {
                                                    writer.write("      " + tipoarr[0] + " param" + i + " = 3;\n");
                                                } else {
                                                    if (tipoarr[0].equals("String")) {
                                                        writer.write("      " + tipoarr[0] + " param" + i + " = \"\";\n");
                                                    } else {
                                                        if (tipoarr[0].equals("date") || tipoarr[0].equals("Date")) {
                                                            writer.write("      " + tipoarr[0] + " param" + i + " = new Date();\n");
                                                        } else {
                                                            if (tipoarr[0].equals("boolean") || tipoarr[0].equals("Boolean")) {
                                                                writer.write("      " + tipoarr[0] + " param" + i + " = true;\n");
                                                            } else {
                                                                writer.write("      " + tipoarr[0] + " param" + i + " = new " + tipoarr[0] + "();\n");
                                                            }
                                                        }
                                                    }
                                                }
                                                i++;
                                            }
                                            writer.write("        Boolean expResult = true;\n");
                                            //Revisar respuesta de la prueba
                                            String tmp = partes[partes.length - 2];
                                            if (tmp.equals("int") || tmp.equals("Integer")) {
                                                writer.write("        " + partes[partes.length - 2] + " result = 0;\n");
                                            } else {
                                                if (tmp.equals("String")) {
                                                    writer.write("        " + partes[partes.length - 2] + " result = \"\";\n");
                                                } else {
                                                    if (tmp.equals("boolean") || tmp.equals("Boolean")) {
                                                        writer.write("        " + partes[partes.length - 2] + " result = false;\n");
                                                    } else {
                                                        writer.write("  int      " + partes[partes.length - 2] + " result = 0;\n");
                                                    }
                                                }
                                            }
                                            writer.write("        try {\n"
                                                    + "            result = " + nn + "." + partes[partes.length - 1] + "(");
                                            i = 1;
                                            for (String param : parametros) {
                                                if (i >= parametros.length) {
                                                    writer.write("param" + i);
                                                } else {
                                                    writer.write("param" + i + ",");
                                                }
                                                i++;
                                            }
                                            //Revisar respuesta de la prueba
                                            writer.write(");\n"
                                                    + "        } catch (Exception e) {\n");
                                            if (tmp.equals("int") || tmp.equals("Integer")) {
                                                writer.write("        result = 0;\n");
                                            } else {
                                                if (tmp.equals("String")) {
                                                    writer.write("        result = \"\";\n");
                                                } else {
                                                    if (tmp.equals("boolean") || tmp.equals("Boolean")) {
                                                        writer.write("        result = false;\n");
                                                    } else {
                                                        writer.write("        result = 0;\n");
                                                    }
                                                }
                                            }
                                            writer.write("        }\n"
                                                    + "        Boolean res = false;\n"
                                                    + "        if (result != 0) {\n"
                                                    + "            res = true;\n"
                                                    + "        } else {\n"
                                                    + "            res = false;\n"
                                                    + "        }\n"
                                                 /*   + "        assertEquals(expResult, res);\n"*/
                                                    + "        Date vfinal = new Date();\n"
                                                    + "        long duracion = Util.DiferenciaFechas(vinicio, vfinal);\n"
                                                    + "        Util.exportar(clase, metodo, duracion);\n"
                                                    
                                            
                                                    + "    }");
                                        }
                                    }
                                } catch (Exception e) {
                                }
                            }
                        }
                        /*
                        //insert, (select, update, delete funcionan de manera similar)
                        scanner = new Scanner(archivo);
                        metodo = "";
                        band = false;
                        while (scanner.hasNextLine()) {
                            final String lineFromFile = scanner.nextLine();
                            if (lineFromFile.toLowerCase().contains("public")) {
                                metodo = lineFromFile;
                                band = true;
                            }
                            if (band) {
                                if ((lineFromFile.toLowerCase().contains("select") || lineFromFile.toLowerCase().contains("Select") || lineFromFile.toLowerCase().contains("SELECT")) && lineFromFile.toLowerCase().contains("insert")) {
                                    try {
                                        String[] partes = metodo.split("\\(");
                                        String[] partes2 = metodo.split("\\(");
                                        String[] parametros = partes2[1].split("\\)");
                                        try {
                                            parametros = parametros[0].split(", ");
                                        } catch (Exception e) {
                                            parametros = null;
                                        }
                                        if (parametros == null || (parametros.length == 1 && parametros[0].length() <= 1)) {
                                            partes = partes[0].split(" ");
                                            writer.write("\n@Test\n"
                                                    + "    public void test" + partes[partes.length - 1] + "() throws Exception {\n"
                                                    + "        System.out.println(\"" + partes[partes.length - 1] + "\");\n"
                                                    + "        String metodo = \"" + partes[partes.length - 1] + "\";\n"
                                                    + "        String clase = \"" + nn + "\";\n"
                                                    + "        Date vinicio = new Date();\n"
                                                    + "        Boolean expResult = true;\n");
                                            String tmp = partes[partes.length - 2];
                                            if (tmp.equals("int") || tmp.equals("Integer")) {
                                                writer.write("        " + partes[partes.length - 2] + " result = 0;\n");
                                            } else {
                                                if (tmp.equals("String")) {
                                                    writer.write("        " + partes[partes.length - 2] + " result = \"\";\n");
                                                } else {
                                                    if (tmp.equals("boolean") || tmp.equals("Boolean")) {
                                                        writer.write("        " + partes[partes.length - 2] + " result = false;\n");
                                                    } else {
                                                        writer.write("        " + partes[partes.length - 2] + " result = null;\n");
                                                    }
                                                }
                                            }
                                            writer.write("        try {\n"
                                                    + "            result = " + nn + "." + partes[partes.length - 1] + "();\n"
                                                    + "        } catch (Exception e) {\n");
                                            if (tmp.equals("int") || tmp.equals("Integer")) {
                                                writer.write("        result = 0;\n");
                                            } else {
                                                if (tmp.equals("String")) {
                                                    writer.write("        result = \"\";\n");
                                                } else {
                                                    if (tmp.equals("boolean") || tmp.equals("Boolean")) {
                                                        writer.write("        result = false;\n");
                                                    } else {
                                                        writer.write("        result = null;\n");
                                                    }
                                                }
                                            }
                                            writer.write("        }\n"
                                                    + "        Boolean res = false;\n"
                                                    + "        if (result != 0) {\n"
                                                    + "            res = true;\n"
                                                    + "        } else {\n"
                                                    + "            res = false;\n"
                                                    + "        }\n"
                                                    + "        assertEquals(expResult, res);\n"
                                                    + "        Date vfinal = new Date();\n"
                                                    + "        long duracion = Util.DiferenciaFechas(vinicio, vfinal);\n"
                                                    + "        Util.exportar(clase, metodo, duracion);\n"
                                                    + "    }");
                                        } else {
                                            partes = partes[0].split(" ");
                                            writer.write("\n@Test\n"
                                                    + "    public void test" + partes[partes.length - 1] + "() throws Exception {\n"
                                                    + "        System.out.println(\"" + partes[partes.length - 1] + "\");\n"
                                                    + "        String metodo = \"" + partes[partes.length - 1] + "\";\n"
                                                    + "        String clase = \"" + nn + "\";\n"
                                                    + "        Date vinicio = new Date();\n"
                                            );
                                            int i = 1;
                                            for (String param : parametros) {
                                                String[] tipoarr = param.split(" ");
                                                if (tipoarr[0].equals("int") || tipoarr[0].equals("Integer")) {
                                                    writer.write("      " + tipoarr[0] + " param" + i + " = 3;\n");
                                                } else {
                                                    if (tipoarr[0].equals("String")) {
                                                        writer.write("      " + tipoarr[0] + " param" + i + " = \"\";\n");
                                                    } else {
                                                        if (tipoarr[0].equals("date") || tipoarr[0].equals("Date")) {
                                                            writer.write("      " + tipoarr[0] + " param" + i + " = new Date();\n");
                                                        } else {
                                                            if (tipoarr[0].equals("boolean") || tipoarr[0].equals("Boolean")) {
                                                                writer.write("      " + tipoarr[0] + " param" + i + " = true;\n");
                                                            } else {
                                                                writer.write("      " + tipoarr[0] + " param" + i + " = new " + tipoarr[0] + "();\n");
                                                            }
                                                        }
                                                    }
                                                }
                                                i++;
                                            }
                                            writer.write("        Boolean expResult = true;\n");
                                            String tmp = partes[partes.length - 2];
                                            if (tmp.equals("int") || tmp.equals("Integer")) {
                                                writer.write("        " + partes[partes.length - 2] + " result = 0;\n");
                                            } else {
                                                if (tmp.equals("String")) {
                                                    writer.write("        " + partes[partes.length - 2] + " result = \"\";\n");
                                                } else {
                                                    if (tmp.equals("boolean") || tmp.equals("Boolean")) {
                                                        writer.write("        " + partes[partes.length - 2] + " result = false;\n");
                                                    } else {
                                                        writer.write("        " + partes[partes.length - 2] + " result = null;\n");
                                                    }
                                                }
                                            }
                                            writer.write("        try {\n"
                                                    + "            result = " + nn + "." + partes[partes.length - 1] + "(");
                                            i = 1;
                                            for (String param : parametros) {
                                                if (i >= parametros.length) {
                                                    writer.write("param" + i);
                                                } else {
                                                    writer.write("param" + i + ",");
                                                }
                                                i++;
                                            }
                                            writer.write(");\n"
                                                    + "        } catch (Exception e) {\n");
                                            if (tmp.equals("int") || tmp.equals("Integer")) {
                                                writer.write("        result = 0;\n");
                                            } else {
                                                if (tmp.equals("String")) {
                                                    writer.write("        result = \"\";\n");
                                                } else {
                                                    if (tmp.equals("boolean") || tmp.equals("Boolean")) {
                                                        writer.write("        result = false;\n");
                                                    } else {
                                                        writer.write("        result = null;\n");
                                                    }
                                                }
                                            }
                                            writer.write("        }\n"
                                                    + "        Boolean res = false;\n"
                                                    + "        if (result != 0) {\n"
                                                    + "            res = true;\n"
                                                    + "        } else {\n"
                                                    + "            res = false;\n"
                                                    + "        }\n"
                                                    + "        assertEquals(expResult, res);\n"
                                                    + "        Date vfinal = new Date();\n"
                                                    + "        long duracion = Util.DiferenciaFechas(vinicio, vfinal);\n"
                                                    + "        Util.exportar(clase, metodo, duracion);\n"
                                                    + "    }");
                                        }
                                    } catch (Exception e) {
                                    }
                                }

                            }
                        }
                         */
                        //insert, (select, update, delete funcionan de manera similar)
                        
                        
                        /******************/
                        
                        
                        scanner = new Scanner(archivo);
                        metodo = "";
                        band = false;
                        //Recorrer la clase por líneas
                        while (scanner.hasNextLine()) {
                            final String lineFromFile = scanner.nextLine();
                            //Busca la palabra reservada "public" para encontrar los métodos
                            if (lineFromFile.toLowerCase().contains("public")) {
                                metodo = lineFromFile;
                                band = true;
                            }
                            //Si encontró algún método
                            if (band) {
                                try {
                                    //Revisa si existe alguna palabra reservada de SQL
                                    if ((lineFromFile.toLowerCase().contains("listar"))) {
                                        //Separa el método en partes para obtener el tipo de respuesta
                                        String[] partes = metodo.split("\\(");
                                        String[] partes2 = metodo.split("\\(");
                                        //Separa el método en partes para obtener los parámetros
                                        String[] parametros = partes2[1].split("\\)");
                                        try {
                                            parametros = parametros[0].split(", ");
                                        } catch (Exception e) {
                                            parametros = null;
                                        }
                                        //Escribir el nombre del caso de prueba y el fragmento para tomar el tiempo
                                        if (parametros == null || (parametros.length == 1 && parametros[0].length() <= 1)) {
                                            partes = partes[0].split(" ");
                                            writer.write("\n@Test\n"
                                                    + "    public void test" + partes[partes.length - 1] + "() throws Exception {\n"
                                                    + "        System.out.println(\"" + partes[partes.length - 1] + "\");\n"
                                                    + "        String metodo = \"" + partes[partes.length - 1] + "\";\n"
                                                    + "        String clase = \"" + nn + "\";\n"
                                                    + "        Date vinicio = new Date();\n"
                                                    + "        Boolean expResult = true;\n");
                                            //Inicializar los parámetros según los encontrados entre los ()
                                            String tmp = partes[partes.length - 2];
                                            //Revisar tipos de datos nativos
                                            if (tmp.equals("int") || tmp.equals("Integer")) {
                                                writer.write("        " + partes[partes.length - 2] + " result = 0;\n");
                                            } else {
                                                if (tmp.equals("String")) {
                                                    writer.write("        " + partes[partes.length - 2] + " result = \"\";\n");
                                                } else {
                                                    if (tmp.equals("boolean") || tmp.equals("Boolean")) {
                                                        writer.write("        " + partes[partes.length - 2] + " result = false;\n");
                                                    } else {
                                                        writer.write("        " + partes[partes.length - 2] + " result = null;\n");
                                                    }
                                                }
                                            }
                                            //Realizar la prueba del resultado del Test
                                            writer.write("        try {\n"
                                                    + "            result = " + nn + "." + partes[partes.length - 1] + "();\n"
                                                    + "        } catch (Exception e) {\n");
                                            //Revisar tipos de datos nativos
                                            if (tmp.equals("int") || tmp.equals("Integer")) {
                                                writer.write("        result = 0;\n");
                                            } else {
                                                if (tmp.equals("String")) {
                                                    writer.write("        result = \"\";\n");
                                                } else {
                                                    if (tmp.equals("boolean") || tmp.equals("Boolean")) {
                                                        writer.write("        result = false;\n");
                                                    } else {
                                                        writer.write("        result = null;\n");
                                                    }
                                                }
                                            }
                                            //Realizar la prueba del resultado del Test
                                            writer.write("        }\n"
                                                    + "        Boolean res = false;\n"
                                                    + "        if (result == null) {\n"
                                                    + "            res = true;\n"
                                                    + "        } else {\n"
                                                    + "            res = false;\n"
                                                    + "        }\n"
                                                    + "        assertEquals(expResult, res);\n"
                                                    + "        Date vfinal = new Date();\n"
                                                    + "        long duracion = Util.DiferenciaFechas(vinicio, vfinal);\n"
                                                    + "        Util.exportar(clase, metodo, duracion);\n"
                                                    + "    }");
                                        } else {
                                            //Escribir el nombre del caso de prueba y el fragmento para tomar el tiempo
                                            partes = partes[0].split(" ");
                                            writer.write("\n@Test\n"
                                                    + "    public void test" + partes[partes.length - 1] + "() throws Exception {\n"
                                                    + "        System.out.println(\"" + partes[partes.length - 1] + "\");\n"
                                                    + "        String metodo = \"" + partes[partes.length - 1] + "\";\n"
                                                    + "        String clase = \"" + nn + "\";\n"
                                                    + "        Date vinicio = new Date();\n"
                                            );
                                            int i = 1;
                                            for (String param : parametros) {
                                                //Revisar tipos de datos nativos
                                                String[] tipoarr = param.split(" ");
                                                if (tipoarr[0].equals("int") || tipoarr[0].equals("Integer")) {
                                                    writer.write("      " + tipoarr[0] + " param" + i + " = 3;\n");
                                                } else {
                                                    if (tipoarr[0].equals("String")) {
                                                        writer.write("      " + tipoarr[0] + " param" + i + " = \"\";\n");
                                                    } else {
                                                        if (tipoarr[0].equals("date") || tipoarr[0].equals("Date")) {
                                                            writer.write("      " + tipoarr[0] + " param" + i + " = new Date();\n");
                                                        } else {
                                                            if (tipoarr[0].equals("boolean") || tipoarr[0].equals("Boolean")) {
                                                                writer.write("      " + tipoarr[0] + " param" + i + " = true;\n");
                                                            } else {
                                                                writer.write("      " + tipoarr[0] + " param" + i + " = new " + tipoarr[0] + "();\n");
                                                            }
                                                        }
                                                    }
                                                }
                                                i++;
                                            }
                                            writer.write("        Boolean expResult = true;\n");
                                            //Revisar respuesta de la prueba
                                            String tmp = partes[partes.length - 2];
                                            if (tmp.equals("int") || tmp.equals("Integer")) {
                                                writer.write("        " + partes[partes.length - 2] + " result = 0;\n");
                                            } else {
                                                if (tmp.equals("String")) {
                                                    writer.write("        " + partes[partes.length - 2] + " result = \"\";\n");
                                                } else {
                                                    if (tmp.equals("boolean") || tmp.equals("Boolean")) {
                                                        writer.write("        " + partes[partes.length - 2] + " result = false;\n");
                                                    } else {
                                                        writer.write("        " + partes[partes.length - 2] + " result = null;\n");
                                                    }
                                                }
                                            }
                                            writer.write("        try {\n"
                                                    + "            result = " + nn + "." + partes[partes.length - 1] + "(");
                                            i = 1;
                                            for (String param : parametros) {
                                                if (i >= parametros.length) {
                                                    writer.write("param" + i);
                                                } else {
                                                    writer.write("param" + i + ",");
                                                }
                                                i++;
                                            }
                                            //Revisar respuesta de la prueba
                                            writer.write(");\n"
                                                    + "        } catch (Exception e) {\n");
                                            if (tmp.equals("int") || tmp.equals("Integer")) {
                                                writer.write("        result = 0;\n");
                                            } else {
                                                if (tmp.equals("String")) {
                                                    writer.write("        result = \"\";\n");
                                                } else {
                                                    if (tmp.equals("boolean") || tmp.equals("Boolean")) {
                                                        writer.write("        result = false;\n");
                                                    } else {
                                                        writer.write("        result = null;\n");
                                                    }
                                                }
                                            }
                                            writer.write("        }\n"
                                                    + "        Boolean res = false;\n"
                                                    + "        if (result == null) {\n"
                                                    + "            res = true;\n"
                                                    + "        } else {\n"
                                                    + "            res = false;\n"
                                                    + "        }\n"
                                                    + "        assertEquals(expResult, res);\n"
                                                    + "        Date vfinal = new Date();\n"
                                                    + "        long duracion = Util.DiferenciaFechas(vinicio, vfinal);\n"
                                                    + "        Util.exportar(clase, metodo, duracion);\n"
                                                    + "    }");
                                        }
                                    }
                                } catch (Exception e) {
                                }
                            }
                        }
                        
                        
                        /*****************************************/
                        
                        
                        
                        
                        
                        
                        
                        /******************/
                        
                        
                        scanner = new Scanner(archivo);
                        metodo = "";
                        band = false;
                        //Recorrer la clase por líneas
                        while (scanner.hasNextLine()) {
                            final String lineFromFile = scanner.nextLine();
                            //Busca la palabra reservada "public" para encontrar los métodos
                            if (lineFromFile.toLowerCase().contains("public")) {
                                metodo = lineFromFile;
                                band = true;
                            }
                            //Si encontró algún método
                            if (band) {
                                try {
                                    //Revisa si existe alguna palabra reservada de SQL
                                    if ((lineFromFile.toLowerCase().contains("eliminar"))) {
                                        //Separa el método en partes para obtener el tipo de respuesta
                                        String[] partes = metodo.split("\\(");
                                        String[] partes2 = metodo.split("\\(");
                                        //Separa el método en partes para obtener los parámetros
                                        String[] parametros = partes2[1].split("\\)");
                                        try {
                                            parametros = parametros[0].split(", ");
                                        } catch (Exception e) {
                                            parametros = null;
                                        }
                                        //Escribir el nombre del caso de prueba y el fragmento para tomar el tiempo
                                        if (parametros == null || (parametros.length == 1 && parametros[0].length() <= 1)) {
                                            partes = partes[0].split(" ");
                                            writer.write("\n@Test\n"
                                                    + "    public void test" + partes[partes.length - 1] + "() throws Exception {\n"
                                                    + "        System.out.println(\"" + partes[partes.length - 1] + "\");\n"
                                                    + "        String metodo = \"" + partes[partes.length - 1] + "\";\n"
                                                    + "        String clase = \"" + nn + "\";\n"
                                                    + "        Date vinicio = new Date();\n"
                                                    + "        Boolean expResult = true;\n");
                                            //Inicializar los parámetros según los encontrados entre los ()
                                            String tmp = partes[partes.length - 2];
                                            //Revisar tipos de datos nativos
                                            if (tmp.equals("int") || tmp.equals("Integer")) {
                                                writer.write("        " + partes[partes.length - 2] + " result = 0;\n");
                                            } else {
                                                if (tmp.equals("String")) {
                                                    writer.write("        " + partes[partes.length - 2] + " result = \"\";\n");
                                                } else {
                                                    if (tmp.equals("boolean") || tmp.equals("Boolean")) {
                                                        writer.write("        " + partes[partes.length - 2] + " result = false;\n");
                                                    } else {
                                                        writer.write("int        " + partes[partes.length - 2] + " result = 0 ;\n");
                                                    }
                                                }
                                            }
                                            //Realizar la prueba del resultado del Test
                                            writer.write("        try {\n"
                                                    + "            result = " + nn + "." + partes[partes.length - 1] + "();\n"
                                                    + "        } catch (Exception e) {\n");
                                            //Revisar tipos de datos nativos
                                            if (tmp.equals("int") || tmp.equals("Integer")) {
                                                writer.write("        result = 0;\n");
                                            } else {
                                                if (tmp.equals("String")) {
                                                    writer.write("        result = \"\";\n");
                                                } else {
                                                    if (tmp.equals("boolean") || tmp.equals("Boolean")) {
                                                        writer.write("        result = false;\n");
                                                    } else {
                                                        writer.write("        result = null;\n");
                                                    }
                                                }
                                            }
                                            //Realizar la prueba del resultado del Test
                                            writer.write("        }\n"
                                                    + "        Boolean res = false;\n"
                                                    + "        if (result == 0) {\n"
                                                    + "            res = true;\n"
                                                    + "        } else {\n"
                                                    + "            res = false;\n"
                                                    + "        }\n"
                                                    + "        assertEquals(expResult, res);\n"
                                                    + "        Date vfinal = new Date();\n"
                                                    + "        long duracion = Util.DiferenciaFechas(vinicio, vfinal);\n"
                                                    + "        Util.exportar(clase, metodo, duracion);\n"
                                                    + "    }");
                                        } else {
                                            //Escribir el nombre del caso de prueba y el fragmento para tomar el tiempo
                                            partes = partes[0].split(" ");
                                            writer.write("\n@Test\n"
                                                    + "    public void test" + partes[partes.length - 1] + "() throws Exception {\n"
                                                    + "        System.out.println(\"" + partes[partes.length - 1] + "\");\n"
                                                    + "        String metodo = \"" + partes[partes.length - 1] + "\";\n"
                                                    + "        String clase = \"" + nn + "\";\n"
                                                    + "        Date vinicio = new Date();\n"
                                            );
                                            int i = 1;
                                            for (String param : parametros) {
                                                //Revisar tipos de datos nativos
                                                String[] tipoarr = param.split(" ");
                                                if (tipoarr[0].equals("int") || tipoarr[0].equals("Integer")) {
                                                    writer.write("      " + tipoarr[0] + " param" + i + " = 3;\n");
                                                } else {
                                                    if (tipoarr[0].equals("String")) {
                                                        writer.write("      " + tipoarr[0] + " param" + i + " = \"\";\n");
                                                    } else {
                                                        if (tipoarr[0].equals("date") || tipoarr[0].equals("Date")) {
                                                            writer.write("      " + tipoarr[0] + " param" + i + " = new Date();\n");
                                                        } else {
                                                            if (tipoarr[0].equals("boolean") || tipoarr[0].equals("Boolean")) {
                                                                writer.write("      " + tipoarr[0] + " param" + i + " = true;\n");
                                                            } else {
                                                                writer.write("      " + tipoarr[0] + " param" + i + " = new " + tipoarr[0] + "();\n");
                                                            }
                                                        }
                                                    }
                                                }
                                                i++;
                                            }
                                            writer.write("        Boolean expResult = true;\n");
                                            //Revisar respuesta de la prueba
                                            String tmp = partes[partes.length - 2];
                                            if (tmp.equals("int") || tmp.equals("Integer")) {
                                                writer.write("        " + partes[partes.length - 2] + " result = 0;\n");
                                            } else {
                                                if (tmp.equals("String")) {
                                                    writer.write("        " + partes[partes.length - 2] + " result = \"\";\n");
                                                } else {
                                                    if (tmp.equals("boolean") || tmp.equals("Boolean")) {
                                                        writer.write("        " + partes[partes.length - 2] + " result = false;\n");
                                                    } else {
                                                        writer.write("        " + partes[partes.length - 2] + " result = null;\n");
                                                    }
                                                }
                                            }
                                            writer.write("        try {\n"
                                                    + "            result = " + nn + "." + partes[partes.length - 1] + "(");
                                            i = 1;
                                            for (String param : parametros) {
                                                if (i >= parametros.length) {
                                                    writer.write("param" + i);
                                                } else {
                                                    writer.write("param" + i + ",");
                                                }
                                                i++;
                                            }
                                            //Revisar respuesta de la prueba
                                            writer.write(");\n"
                                                    + "        } catch (Exception e) {\n");
                                            if (tmp.equals("int") || tmp.equals("Integer")) {
                                                writer.write("        result = 0;\n");
                                            } else {
                                                if (tmp.equals("String")) {
                                                    writer.write("        result = \"\";\n");
                                                } else {
                                                    if (tmp.equals("boolean") || tmp.equals("Boolean")) {
                                                        writer.write("        result = false;\n");
                                                    } else {
                                                        writer.write(" int       result = 0 ;\n");
                                                    }
                                                }
                                            }
                                            writer.write("        }\n"
                                                    + "        Boolean res = false;\n"
                                                    + "        if (result == 0) {\n"
                                                    + "            res = true;\n"
                                                    + "        } else {\n"
                                                    + "            res = false;\n"
                                                    + "        }\n"
                                                    + "        assertEquals(expResult, res);\n"
                                                    + "        Date vfinal = new Date();\n"
                                                    + "        long duracion = Util.DiferenciaFechas(vinicio, vfinal);\n"
                                                    + "        Util.exportar(clase, metodo, duracion);\n"
                                                    + "    }");
                                        }
                                    }
                                } catch (Exception e) {
                                }
                            }
                        }
                        
                        
                        /*****************************************/
                        
                        
                        
                        /*
                        
                        //update, (insert, select, delete funcionan de manera similar)
                        scanner = new Scanner(archivo);
                        metodo = "";
                        band = false;
                        while (scanner.hasNextLine()) {
                            final String lineFromFile = scanner.nextLine();
                            if (lineFromFile.toLowerCase().contains("public")) {
                                metodo = lineFromFile;
                                band = true;
                            }
                            if (band) {
                                if ((lineFromFile.toLowerCase().contains("select") || lineFromFile.toLowerCase().contains("Select") || lineFromFile.toLowerCase().contains("SELECT")) && lineFromFile.toLowerCase().contains("update")) {
                                    try {
                                        String[] partes = metodo.split("\\(");
                                        String[] partes2 = metodo.split("\\(");
                                        String[] parametros = partes2[1].split("\\)");
                                        try {
                                            parametros = parametros[0].split(", ");
                                        } catch (Exception e) {
                                            parametros = null;
                                        }
                                        if (parametros == null || (parametros.length == 1 && parametros[0].length() <= 1)) {
                                            partes = partes[0].split(" ");
                                            writer.write("\n@Test\n"
                                                    + "    public void test" + partes[partes.length - 1] + "() throws Exception {\n"
                                                    + "        System.out.println(\"" + partes[partes.length - 1] + "\");\n"
                                                    + "        String metodo = \"" + partes[partes.length - 1] + "\";\n"
                                                    + "        String clase = \"" + nn + "\";\n"
                                                    + "        Date vinicio = new Date();\n"
                                                    + "        Boolean expResult = true;\n");
                                            String tmp = partes[partes.length - 2];
                                            if (tmp.equals("int") || tmp.equals("Integer")) {
                                                writer.write("        " + partes[partes.length - 2] + " result = 0;\n");
                                            } else {
                                                if (tmp.equals("String")) {
                                                    writer.write("        " + partes[partes.length - 2] + " result = \"\";\n");
                                                } else {
                                                    if (tmp.equals("boolean") || tmp.equals("Boolean")) {
                                                        writer.write("        " + partes[partes.length - 2] + " result = false;\n");
                                                    } else {
                                                        writer.write("        " + partes[partes.length - 2] + " result = null;\n");
                                                    }
                                                }
                                            }
                                            writer.write("        try {\n"
                                                    + "            result = " + nn + "." + partes[partes.length - 1] + "();\n"
                                                    + "        } catch (Exception e) {\n");
                                            if (tmp.equals("int") || tmp.equals("Integer")) {
                                                writer.write("        result = 0;\n");
                                            } else {
                                                if (tmp.equals("String")) {
                                                    writer.write("        result = \"\";\n");
                                                } else {
                                                    if (tmp.equals("boolean") || tmp.equals("Boolean")) {
                                                        writer.write("        result = false;\n");
                                                    } else {
                                                        writer.write("        result = null;\n");
                                                    }
                                                }
                                            }
                                            writer.write("        }\n"
                                                    + "        Boolean res = false;\n"
                                                    + "        if (result != false) {\n"
                                                    + "            res = true;\n"
                                                    + "        } else {\n"
                                                    + "            res = false;\n"
                                                    + "        }\n"
                                                    + "        assertEquals(expResult, res);\n"
                                                    + "        Date vfinal = new Date();\n"
                                                    + "        long duracion = Util.DiferenciaFechas(vinicio, vfinal);\n"
                                                    + "        Util.exportar(clase, metodo, duracion);\n"
                                                    + "    }");
                                        } else {
                                            partes = partes[0].split(" ");
                                            writer.write("\n@Test\n"
                                                    + "    public void test" + partes[partes.length - 1] + "() throws Exception {\n"
                                                    + "        System.out.println(\"" + partes[partes.length - 1] + "\");\n"
                                                    + "        String metodo = \"" + partes[partes.length - 1] + "\";\n"
                                                    + "        String clase = \"" + nn + "\";\n"
                                                    + "        Date vinicio = new Date();\n"
                                            );
                                            int i = 1;
                                            for (String param : parametros) {
                                                String[] tipoarr = param.split(" ");
                                                if (tipoarr[0].equals("int") || tipoarr[0].equals("Integer")) {
                                                    writer.write("      " + tipoarr[0] + " param" + i + " = 3;\n");
                                                } else {
                                                    if (tipoarr[0].equals("String")) {
                                                        writer.write("      " + tipoarr[0] + " param" + i + " = \"\";\n");
                                                    } else {
                                                        if (tipoarr[0].equals("date") || tipoarr[0].equals("Date")) {
                                                            writer.write("      " + tipoarr[0] + " param" + i + " = new Date();\n");
                                                        } else {
                                                            if (tipoarr[0].equals("boolean") || tipoarr[0].equals("Boolean")) {
                                                                writer.write("      " + tipoarr[0] + " param" + i + " = true;\n");
                                                            } else {
                                                                writer.write("      " + tipoarr[0] + " param" + i + " = new " + tipoarr[0] + "();\n");
                                                            }
                                                        }
                                                    }
                                                }
                                                i++;
                                            }
                                            writer.write("        Boolean expResult = true;\n");
                                            String tmp = partes[partes.length - 2];
                                            if (tmp.equals("int") || tmp.equals("Integer")) {
                                                writer.write("        " + partes[partes.length - 2] + " result = 0;\n");
                                            } else {
                                                if (tmp.equals("String")) {
                                                    writer.write("        " + partes[partes.length - 2] + " result = \"\";\n");
                                                } else {
                                                    if (tmp.equals("boolean") || tmp.equals("Boolean")) {
                                                        writer.write("        " + partes[partes.length - 2] + " result = false;\n");
                                                    } else {
                                                        writer.write("        " + partes[partes.length - 2] + " result = null;\n");
                                                    }
                                                }
                                            }
                                            writer.write("        try {\n"
                                                    + "            result = " + nn + "." + partes[partes.length - 1] + "(");
                                            i = 1;
                                            for (String param : parametros) {
                                                if (i >= parametros.length) {
                                                    writer.write("param" + i);
                                                } else {
                                                    writer.write("param" + i + ",");
                                                }
                                                i++;
                                            }
                                            writer.write(");\n"
                                                    + "        } catch (Exception e) {\n");
                                            if (tmp.equals("int") || tmp.equals("Integer")) {
                                                writer.write("        result = 0;\n");
                                            } else {
                                                if (tmp.equals("String")) {
                                                    writer.write("        result = \"\";\n");
                                                } else {
                                                    if (tmp.equals("boolean") || tmp.equals("Boolean")) {
                                                        writer.write("        result = false;\n");
                                                    } else {
                                                        writer.write("        result = null;\n");
                                                    }
                                                }
                                            }
                                            writer.write("        }\n"
                                                    + "        Boolean res = false;\n"
                                                    + "        if (result != false) {\n"
                                                    + "            res = true;\n"
                                                    + "        } else {\n"
                                                    + "            res = false;\n"
                                                    + "        }\n"
                                                    + "        assertEquals(expResult, res);\n"
                                                    + "        Date vfinal = new Date();\n"
                                                    + "        long duracion = Util.DiferenciaFechas(vinicio, vfinal);\n"
                                                    + "        Util.exportar(clase, metodo, duracion);\n"
                                                    + "    }");
                                        }
                                    } catch (Exception e) {
                                    }
                                }

                            }
                        }*/
                        
                        
                        /**********************************/
                        
                        /*
                        //delete, (insert, update, select funcionan de manera similar)
                        scanner = new Scanner(archivo);
                        metodo = "";
                        band = false;
                        while (scanner.hasNextLine()) {
                            final String lineFromFile = scanner.nextLine();
                            if (lineFromFile.toLowerCase().contains("public")) {
                                metodo = lineFromFile;
                                band = true;
                            }
                            if (band) {
                                if ((lineFromFile.toLowerCase().contains("select") || lineFromFile.toLowerCase().contains("Select") || lineFromFile.toLowerCase().contains("SELECT")) && lineFromFile.toLowerCase().contains("delete")) {
                                    try {
                                        String[] partes = metodo.split("\\(");
                                        String[] partes2 = metodo.split("\\(");
                                        String[] parametros = partes2[1].split("\\)");
                                        try {
                                            parametros = parametros[0].split(", ");
                                        } catch (Exception e) {
                                            parametros = null;
                                        }
                                        if (parametros == null || (parametros.length == 1 && parametros[0].length() <= 1)) {
                                            partes = partes[0].split(" ");
                                            writer.write("\n@Test\n"
                                                    + "    public void test" + partes[partes.length - 1] + "() throws Exception {\n"
                                                    + "        System.out.println(\"" + partes[partes.length - 1] + "\");\n"
                                                    + "        String metodo = \"" + partes[partes.length - 1] + "\";\n"
                                                    + "        String clase = \"" + nn + "\";\n"
                                                    + "        Date vinicio = new Date();\n"
                                                    + "        Boolean expResult = true;\n");
                                            String tmp = partes[partes.length - 2];
                                            if (tmp.equals("int") || tmp.equals("Integer")) {
                                                writer.write("        " + partes[partes.length - 2] + " result = 0;\n");
                                            } else {
                                                if (tmp.equals("String")) {
                                                    writer.write("        " + partes[partes.length - 2] + " result = \"\";\n");
                                                } else {
                                                    if (tmp.equals("boolean") || tmp.equals("Boolean")) {
                                                        writer.write("        " + partes[partes.length - 2] + " result = false;\n");
                                                    } else {
                                                        writer.write("        " + partes[partes.length - 2] + " result = null;\n");
                                                    }
                                                }
                                            }
                                            writer.write("        try {\n"
                                                    + "            result = " + nn + "." + partes[partes.length - 1] + "();\n"
                                                    + "        } catch (Exception e) {\n");
                                            if (tmp.equals("int") || tmp.equals("Integer")) {
                                                writer.write("        result = 0;\n");
                                            } else {
                                                if (tmp.equals("String")) {
                                                    writer.write("        result = \"\";\n");
                                                } else {
                                                    if (tmp.equals("boolean") || tmp.equals("Boolean")) {
                                                        writer.write("        result = false;\n");
                                                    } else {
                                                        writer.write("        result = null;\n");
                                                    }
                                                }
                                            }
                                            writer.write("        }\n"
                                                    + "        Boolean res = false;\n"
                                                    + "        if (result != false) {\n"
                                                    + "            res = true;\n"
                                                    + "        } else {\n"
                                                    + "            res = false;\n"
                                                    + "        }\n"
                                                    + "        assertEquals(expResult, res);\n"
                                                    + "        Date vfinal = new Date();\n"
                                                    + "        long duracion = Util.DiferenciaFechas(vinicio, vfinal);\n"
                                                    + "        Util.exportar(clase, metodo, duracion);\n"
                                                    + "    }");
                                        } else {
                                            partes = partes[0].split(" ");
                                            writer.write("\n@Test\n"
                                                    + "    public void test" + partes[partes.length - 1] + "() throws Exception {\n"
                                                    + "        System.out.println(\"" + partes[partes.length - 1] + "\");\n"
                                                    + "        String metodo = \"" + partes[partes.length - 1] + "\";\n"
                                                    + "        String clase = \"" + nn + "\";\n"
                                                    + "        Date vinicio = new Date();\n"
                                            );
                                            int i = 1;
                                            for (String param : parametros) {
                                                String[] tipoarr = param.split(" ");
                                                if (tipoarr[0].equals("int") || tipoarr[0].equals("Integer")) {
                                                    writer.write("      " + tipoarr[0] + " param" + i + " = 3;\n");
                                                } else {
                                                    if (tipoarr[0].equals("String")) {
                                                        writer.write("      " + tipoarr[0] + " param" + i + " = \"\";\n");
                                                    } else {
                                                        if (tipoarr[0].equals("date") || tipoarr[0].equals("Date")) {
                                                            writer.write("      " + tipoarr[0] + " param" + i + " = new Date();\n");
                                                        } else {
                                                            if (tipoarr[0].equals("boolean") || tipoarr[0].equals("Boolean")) {
                                                                writer.write("      " + tipoarr[0] + " param" + i + " = true;\n");
                                                            } else {
                                                                writer.write("      " + tipoarr[0] + " param" + i + " = new " + tipoarr[0] + "();\n");
                                                            }
                                                        }
                                                    }
                                                }
                                                i++;
                                            }
                                            writer.write("        Boolean expResult = true;\n");
                                            String tmp = partes[partes.length - 2];
                                            if (tmp.equals("int") || tmp.equals("Integer")) {
                                                writer.write("        " + partes[partes.length - 2] + " result = 0;\n");
                                            } else {
                                                if (tmp.equals("String")) {
                                                    writer.write("        " + partes[partes.length - 2] + " result = \"\";\n");
                                                } else {
                                                    if (tmp.equals("boolean") || tmp.equals("Boolean")) {
                                                        writer.write("        " + partes[partes.length - 2] + " result = false;\n");
                                                    } else {
                                                        writer.write("        " + partes[partes.length - 2] + " result = null;\n");
                                                    }
                                                }
                                            }
                                            writer.write("        try {\n"
                                                    + "            result = " + nn + "." + partes[partes.length - 1] + "(");
                                            i = 1;
                                            for (String param : parametros) {
                                                if (i >= parametros.length) {
                                                    writer.write("param" + i);
                                                } else {
                                                    writer.write("param" + i + ",");
                                                }
                                                i++;
                                            }
                                            writer.write(");\n"
                                                    + "        } catch (Exception e) {\n");
                                            if (tmp.equals("int") || tmp.equals("Integer")) {
                                                writer.write("        result = 0;\n");
                                            } else {
                                                if (tmp.equals("String")) {
                                                    writer.write("        result = \"\";\n");
                                                } else {
                                                    if (tmp.equals("boolean") || tmp.equals("Boolean")) {
                                                        writer.write("        result = false;\n");
                                                    } else {
                                                        writer.write("        result = null;\n");
                                                    }
                                                }
                                            }
                                            writer.write("        }\n"
                                                    + "        Boolean res = false;\n"
                                                    + "        if (result != false) {\n"
                                                    + "            res = true;\n"
                                                    + "        } else {\n"
                                                    + "            res = false;\n"
                                                    + "        }\n"
                                                    + "        assertEquals(expResult, res);\n"
                                                    + "        Date vfinal = new Date();\n"
                                                    + "        long duracion = Util.DiferenciaFechas(vinicio, vfinal);\n"
                                                    + "        Util.exportar(clase, metodo, duracion);\n"
                                                    + "    }");
                                        }
                                    } catch (Exception e) {
                                    }
                                }

                            }
                        }*/
                        /******************************************/
                        
                        writer.write("}\n");
                        writer.close();
                    } catch (Exception e) {
                        String tmp = e.getMessage();
                    }

                }

            }
            /*BufferedWriter writer = null;
            writer = new BufferedWriter(new FileWriter(logFile, true));
             */
        } catch (Exception e) {
            salidaa.setText(e.getMessage());
        }
        Date vfinal = new Date();
        long duracion = DiferenciaFechas(inicio, vfinal);
        durac.setText(String.valueOf(duracion) + " milisegundos");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PRINCIPAL().setVisible(true);
            }
        });
    }

    public static long DiferenciaFechas(Date vinicio, Date vfinal) {

        String sinicio = null, sfinal = null;
        Date dinicio = null, dfinal = null;
        long milis1, milis2, diff;

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS");

        try {
            // PARSEO STRING A DATE
            sinicio = sdf.format(vinicio);
            sfinal = sdf.format(vfinal);
            dinicio = sdf.parse(sinicio);
            dfinal = sdf.parse(sfinal);

        } catch (ParseException e) {

            System.out.println("Se ha producido un error en el parseo");
        }

        //INSTANCIA DEL CALENDARIO GREGORIANO
        Calendar cinicio = Calendar.getInstance();
        Calendar cfinal = Calendar.getInstance();

        //ESTABLECEMOS LA FECHA DEL CALENDARIO CON EL DATE GENERADO ANTERIORMENTE
        cinicio.setTime(dinicio);
        cfinal.setTime(dfinal);

        milis1 = cinicio.getTimeInMillis();

        milis2 = cfinal.getTimeInMillis();

        diff = milis2 - milis1;

        return diff;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel durac;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblsel;
    private javax.swing.JLabel salidaa;
    // End of variables declaration//GEN-END:variables
}
